name: CI-CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install --upgrade pip && pip install -r requirements.txt
      - run: pytest

  build-and-push:
    name: Build and Push
    needs: test
    runs-on: ubuntu-latest
    
    if: github.event_name != 'pull_request'
    
    permissions:
      packages: write
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.IMAGE_PUSH_TOKEN }}

      - name: Extract metadata for docker/build-push-action
        id: mata
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository}}

      # - name: Set lowercase image name
      #   run: |
      #     IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
      #     echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags:  ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}